services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["sh", "-c", "ollama serve & sleep 2 && ollama pull mistral && wait"]

  backend:
    build: .
    network_mode: host
    depends_on:
      ollama:
        condition: service_started